var topics =
[
    [ "Chamber Camera", "group__camera.html", "group__camera" ],
    [ "SEM Control", "group__sem.html", "group__sem" ],
    [ "DRW - DrawBeam", "group__draw_beam.html", "group__draw_beam" ],
    [ "EDS", "group__eds.html", "group__eds" ],
    [ "EDX Scanning", "group__edx_scan.html", "group__edx_scan" ],
    [ "FIB Control", "group__fib.html", "group__fib" ],
    [ "GIS - Gas Injection System", "group___gis.html", "group___gis" ],
    [ "SEM GUI Control", "group__sem_gui.html", "group__sem_gui" ],
    [ "FIB GUI Control", "group__fib_gui.html", "group__fib_gui" ],
    [ "Communication", "group__communication.html", "group__communication" ],
    [ "Progress Indication", "group__progress.html", "group__progress" ],
    [ "Input dialog", "group__input.html", "group__input" ],
    [ "Miscellaneous", "group__misc.html", "group__misc" ],
    [ "Power interface", "group__power.html", "group__power" ],
    [ "Chamber", "group__chamber.html", "group__chamber" ],
    [ "Nanomanipulator", "group__nanomanipulator.html", "group__nanomanipulator" ],
    [ "Detector and shutter manipulation", "group__nose.html", "group__nose" ],
    [ "Presets", "group__presets.html", "group__presets" ],
    [ "RCA - Rotating Chord Algorithm", "group__rca.html", "group__rca" ],
    [ "Sample stage layout", "group__sample.html", "group__sample" ],
    [ "TESCAN StreamFiles", "group__stream_files.html", "group__stream_files" ],
    [ "Shutter Control", "group__shutter.html", "group__shutter" ],
    [ "Stage Control", "group__stage.html", "group__stage" ],
    [ "TOF", "group___tofwerk.html", "group___tofwerk" ],
    [ "Airlock - general purpose", "group__airlock.html", "group__airlock" ],
    [ "Airlock 1 - manual", "group__airlock1.html", "group__airlock1" ],
    [ "Airlock 2 - motorized", "group__airlock2.html", "group__airlock2" ]
];